### ISSUE TITLE
defaultLocation not modified in edit page or view page 

### ISSUE THREAD

**Issue by spectra10008** [cheesegrits/filament-google-maps#102]
Hello , 
i have this issue that defaultLocation not modified to my new location , still marker appear in a default location not my new location that i saved.

**Comment by spectra10008** [comment]
![Uploading Screenshot 2024-05-01 at 5.22.21 PM.png…]()

**Comment by sstottelaar** [comment]
Did you end up finding a solution?

**Comment by sstottelaar** [comment]
I ended up needing this on my model:

```php
protected $appends = [
      'location',
  ];
```

**Comment by amrmsccs** [comment]
@sstottelaar   Did you guys find any solution?

**Comment by amrmsccs** [comment]
> I ended up needing this on my model:
> 
> ```
> protected $appends = [
>       'location',
>   ];
> ```

Didn't work with me still getting error location is not afield in your database.
Hope someone got solution.

**Comment by ryanmortier** [comment]
Same issue :(

**Comment by ryanmortier** [comment]
Until that is merged, if anyone is looking for a quick fix then extend the component and put that fix in. Remember to change your form field to use your class.

```php
<?php

namespace App\Forms\Components;

use Exception;

class Map extends \Cheesegrits\FilamentGoogleMaps\Fields\Map
{
    public function getState(): mixed
    {
        $state = parent::getState();

        if (is_array($state)) {
            if (empty(array_filter($state))) {
                return $this->getDefaultLocation();
            }

            return $state;
        } else {
            try {
                return @json_decode($state, true, 512, JSON_THROW_ON_ERROR);
            } catch (Exception $e) {
                return $this->getDefaultLocation();
            }
        }
    }
}

```

**Comment by Heyian** [comment]
Hey there. I've merged the PR associated with this issue onto my fork so we can all get all these goodies from a single place. I gave credits to the person who made the PR in the commits, changelog and in the releases.
I've also credited cheesegrits for his work on the repo and made it clear this was a fork on top of the Readme. I'm not trying to hijack anything, I just want to be able to use all the good solutions people put in the pull requests and I thought I'd made this available to all. If you're interested in this version or want to contribute, you can find my fork at : [Heyian/forkMain](https://github.com/Heyian/filament-google-maps)

I'm open to suggestions on how to move forward from here, simply open up an issue in my fork so we can chat about it.
Thanks.
