### ISSUE TITLE
Method Cheesegrits\FilamentGoogleMaps\Fields\Geocomplete::placesField does not exist

### ISSUE THREAD

**Issue by dallen-aupe** [cheesegrits/filament-google-maps#113]
This is from `README.md` but this does not exist:

https://github.com/cheesegrits/filament-google-maps/blob/39c33d8097d71535e397e9a1f62ee1e4227c12d0/README.md?plain=1#L630

**Comment by Heyian** [comment]
This is fixed by PR #117 by @trippo. The fix is part of the fork I made to get many fixes until @cheesegrits gets back to this repo. You can find the fork here : https://github.com/Heyian/filament-google-maps

**Comment by Heyian** [comment]
The real method is ->placeField(), it was a typo in the Readme. It has now been merged to the repo and the method is documented the right way now. 

Thank you for pointing this out.
