### ISSUE TITLE
Cache issue

### ISSUE THREAD

**Issue by jbuitt** [cheesegrits/filament-google-maps#114]
Hey there!

Thank you for this plugin! However, when I attempt to use MapColumn::make('location') on a table, I get the following database error:

```
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xFF\xD8\xFF\xE0\x00\x10...' for column 'value' at row 1 (Connection: mysql, SQL: insert into `cache` (`key`, `value`, `expiration`) values (fgm-58403c7e07da5762f92a2b9d0c7ac898, s:12403:"<binary data>";, 1725803535) on duplicate key update `key` = values(`key`), `value` = values(`value`), `expiration` = values(`expiration`))
```

Any ideas what may be causing this?

Thank you!

Versions:
Laravel: 11.14.0
PHP: 8.3.9
Filament: v3.2.71
Livewire: v3.5.2

From composer.json:
"cheesegrits/filament-google-maps": "^3.0",

**Comment by kingmaker-agm** [comment]
This Error happened with the **Database _cache driver_**.

Try to use a different cache driver such as **Redis** or something else.

**Comment by jbuitt** [comment]
Awesome. Yup, that was definitely it. Thank you!
