### ISSUE TITLE
Map not loaded with provided lat and lng in production (shared hosting)

### ISSUE THREAD

**Issue by ihsan606** [cheesegrits/filament-google-maps#120]
For example when create a data contain location (lat, lng), map work properly.
but when view created data, map show blank

![image](https://github.com/user-attachments/assets/29120a23-3f28-4dff-81a3-4d9165b9cd02)

**Comment by Heyian** [comment]
We'll need a little more info to be able to help you out. Can you post the code from your form?
Does the console log shows anything?

**Comment by akbarr13** [comment]
i fixed it by disabling psr extension on php
