### ISSUE TITLE
Zoom property $zoom is not working in the Google Map Widget

### ISSUE THREAD

**Issue by kingmaker-agm** [cheesegrits/filament-google-maps#121]
## Issue

I'm using the Google Map Widget (extending `Cheesegrits\FilamentGoogleMaps\Widgets\MapWidget`) in my Filament App.

I have set the **Zoom value** using the class property.
```php
protected static ?int $zoom = 8;
```

### Expected Behavior
The Google Map widget would have Zoom out (to the level of 8)

### Actual Behavior
But the Zoom values are not reflected in the rendered Widget. The Map is **Zoomed In** to the _maximum level_ (level 20)

### Example
![Actual Screenshot](https://storage.googleapis.com/sharing-kingmaker/online-reference/communities/github/filament-google-maps/widget-map-zoom-not-working.png)

## Other Questions

I have a Couple **more questions** regarding the **Map Widget** as well.

1) How can I change the `data` (obtained from the `$this->getData()`) to be reflected in the displayed Map?
2) How to programmatically update the **Markers** in the Widget from within the _Widget class_?

**Comment by navidsafavi** [comment]
@kingmaker-agm use this option
`    protected static ?bool $fitToBounds = false;
`

**Comment by kingmaker-agm** [comment]
This helped me to solve the Issue.

**Comment by kingmaker-agm** [comment]
Can someone help me with the Questions in the Issue #122 ?
