### ISSUE TITLE
Is this plugin still maintained?

### ISSUE THREAD

**Issue by dutypro** [cheesegrits/filament-google-maps#125]
12 PR's outstanding. Number of issues still outstanding.

If not, let me know and I'll fork and look at releasing an updated version.

**Comment by Heyian** [comment]
I'm not sure to be honest. I created a fork lately which include 7 of these PRs. I'll add the last 2 PRs probably this week or the next. My main objective was to have a single place to have access to some of these really good PRs.

If you have feedback about his I'd be glad to hear it.
You can find the fork at [this repo.](https://github.com/Heyian/filament-google-maps)

**Comment by bardolf69** [comment]
@Heyian So I'm using your fork (thanks for doing that and saving me the trouble :) ).  I'll watch this tread for updates on whether Cheesegrits returns or you make your fork official.

**Comment by dutypro** [comment]
@Heyian would you consider making this official and getting it deployable through composer?

**Comment by Heyian** [comment]
I'm working on something to make sure this package gets maintained, I suggest you all subscribe to this thread for an annoucement soon. Thanks for your feedback, it's much appreciated.

**Comment by Heyian** [comment]
@dutypro @bardolf69 

Hi everyone, @cheesegrits is back and I'm helping him maintain this package now. Give us some time and we'll go through the current issues. He had some health issues but it all seem to be resolved. He's still the core maintainer, we had a really good voice chat session yesterday and to be honest, I'm really glad he's back. He's just way more experienced and knowledgeable and not just on his repo but on Laravel, Filament, Google Maps and probably much more. 

I now have the rights to push to this repo if it's needed, so if something else happens, I really hope not, I'll be able to keep maintaining this package while he recovers. This is to say that you should feel safe using this package, the future maintenance of it is assured.

All the modifications that were made on my fork are now merged in this package, so you can all get back to this original repo. I'll keep my fork online for a while to get everyone time to get back to this repo but it won't be maintained anymore. I've put a message at the top of the Readme file but I have no way to reach people who are using it. If anyone has a suggestion/feedback on this, it would help me a lot.

I highly suggest that you all change your composer.json file and get back on this repo if you worked with my fork.

Thank you all for your patience and feedback and thanks to @cheesegrits for making this package, I'm glad you're back and I'm especially glad that you got back on your feet.

Take care!

**Comment by bardolf69** [comment]
@Heyian @cheesegrits Wow FANTASTIC news to hear things are back on track.

**Comment by holmesadam** [comment]
Hey @Heyian - do you have any news on this? Thanks

**Comment by FlorianW208** [comment]
V4 comes tomorrow, whats up @Heyian ?
