### ISSUE TITLE
laravel 11 Undefined variable $getMapType

### ISSUE THREAD

**Issue by agelospanagiotakis** [cheesegrits/filament-google-maps#127]
any clues why it crashes on my installation on this line ?
i am using version  v3.0.16
mapType: @js($getMapType()),

vendor /cheesegrits /filament-google-maps /resources /views /fields /filament-google-maps.blade.php: 57

**Comment by Saifallak** [comment]
having same problem, it messed up in last release, just force it to use 3.0.15 instead of 3.0.16
as 3.0.16 has breaking changes you can see here https://github.com/cheesegrits/filament-google-maps/compare/v3.0.15...v3.0.16

**Comment by Heyian** [comment]
There is indeed a bug on the blade view. I'll try to fix it tonight, worst case I'll do it tomorrow. Thank you for issuing this.

**Comment by mkwsra** [comment]
Thank you for planning to fix it as I needed it also 😅

**Comment by thanhansoft** [comment]
I same, please help me

**Comment by jeevanthelife** [comment]
any updates @Heyian  ??

**Comment by Heyian** [comment]
I'm sorry for being late, had to make chanegs to my local dev to make sure I can test properly each PR and fixes. Now that this is done, I confirm that #126 fixes this issue. I'll make sure this gets merged soon.

**Comment by Naderabdou** [comment]
I found a temporary solution to the issue. By removing the variable $getMapType from the code, it works fine. Here is the modified line: mapType: 'your_default_map_type', // Replace with your default map type

**Comment by nezaboravi** [comment]
Same issue, just to push visibility

**Comment by Naderabdou** [comment]
> Same issue, just to push visibility

It worked for me.
Please remove mapType from the vendor/cheesegrits/filament-google-maps/resources/views/fields/filament-google-maps.blade.php file and try again.

**Comment by Heyian** [comment]
The PR was merged and a new release was built. I just tested it and it works fine on my side. Can anyone else confirm please?

**Comment by nezaboravi** [comment]
> The PR was merged and a new release was built. I just tested it and it works fine on my side. Can anyone else confirm please?

Works, just tried it out.
