### ISSUE TITLE
DrawerManager

### ISSUE THREAD

**Issue by AppCleanSpace** [cheesegrits/filament-google-maps#15]
It is possible to enable the drawerControl, I need it to manage some geofences and it took me a lot of work to find the way to do it. thank you very much for any help possible

**Comment by cheesegrits** [comment]
Do you mean the drawing library?  I'm not aware of a drawerControl?

**Comment by ubpon** [comment]
Hey @AppCleanSpace please check version 1.0.13 it will cater what you need like google drawing manager. You can draw using drawing tools (Circle, Polygon, Rectangle and etc.) and get all the coordinates you wanted in JSON Format.

The issue I experienced right now is the editing or populating of data from DB to input text field specified because it displays 
```
[Object Object]
```

**Comment by AppCleanSpace** [comment]
> Hola, @AppCleanSpace, por favor, comprueba la versión 1.0.13, se encargará de lo que necesitas, como el gestor de dibujos de Google. Puedes dibujar usando herramientas de dibujo (Círculo, Polígono, Rectángulo, etc.) y obtener todas las coordenadas que querías en formato JSON.
> 
> El problema que experimenté en este momento es la edición o el llenado de datos de la base de datos al campo de texto de entrada especificado porque se muestra
> 
> ```
> [Object Object]
> ```

> ¿Te refieres a la biblioteca de dibujos? ¿No conozco un control de cajón?

"Hello, perhaps I didn't explain myself correctly. I have been reviewing GEOJSON and it seems like an excellent tool that is in line with what I want to do. For example, in JavaScript I can enable drawing tools with `google.maps.drawing.DrawingManager`, with which I can delimit the geofence on the map. My intention is to store the JSON with the polygon coordinates so that I can redraw it on the map and present it later. Maybe I'm asking for too much, but my life would be easier if someone could help me."

**Comment by AppCleanSpace** [comment]
> Hola, @AppCleanSpace, por favor, comprueba la versión 1.0.13, se encargará de lo que necesitas, como el gestor de dibujos de Google. Puedes dibujar usando herramientas de dibujo (Círculo, Polígono, Rectángulo, etc.) y obtener todas las coordenadas que querías en formato JSON.
> 
> El problema que experimenté en este momento es la edición o el llenado de datos de la base de datos al campo de texto de entrada especificado porque se muestra
> 
> ```
> [Object Object]
> ```

Tienes toda la razón ubpon he logrado activar las herramientas con otros plugins pero no he podido almacenar ni extraerlas de la base de datos, has avanzando en algo con eso?

**Comment by cheesegrits** [comment]
I added support for the drawing tools in v3.  It isn't documented yet, as it's still WIP, but adding ->drawingControl() to the Map field will enable them.  It works fine for drawing on a new record, but editing an existing record I'm trying to fix an issue where you can't edit previously drawn polygons.  I'd welcome a PR ...

**Comment by waelkhalifa** [comment]
Hey, @cheesegrits  is there any update on this issue ? How can I get the credentials after adding --f-----`->drawingControl()`

**Comment by duncan-chig** [comment]
What credentials are these you asking for? have been  looking at this matter some month ago

**Comment by waelkhalifa** [comment]
@duncan-chig I want to get the data after drawing and store it in database is it possible to do so ?

**Comment by duncan-chig** [comment]
Oh i see @waelkhalifa . Yes it very possible.

Depending on approach, it boils down to having a field (hidden field ) where you store your json coordinates to your db table. 
Example, when using laravel Filament: In your own prefered table, e.g geofences, have coordinates and location columns mapped to corresponding coordinates and location  UI input fields:

```
 ->schema([
                                // hidden field
                                Hidden::make('coordinates') // save & retrieve raw google geoJson in coordinates column in your table
                                    ->label('Coordinates'), 
                                 Map::make('location') // location field in db table
                                    ->height(fn () => '400px')
                                    ->defaultZoom(5)
                                    ->autocomplete('address')
                                    ->autocompleteReverse(true)
                                    ->defaultLocation([29, -24])  // whatever your prefered centroid
                                    ->geolocateLabel('Get Location')
                                    ->geolocateOnLoad(true, false)
                                    ->drawingControl()
                                    ->drawingField('coordinates') // points to your hidden field above
```
When editing, it depends how you setup but a relationship in your model will make life super easy to return the geoJson data from your table and automatically draws the fence for you again.

-  you can edit by moving around  points and re-save. other functinality can be custom to extend what this can do. Hope it helps.

**Comment by waelkhalifa** [comment]
@duncan-chig thank you so much 🙏🏻 I try to work on it now

**Comment by JakeOcean** [comment]
@cheesegrits Nice work on this package!

Can you offer any tips for testing the drawing?  Is it possible to add drawing to the MapTable Widget?

I'm upgrading an older Laravel site that uses Polygons to draw on a map, and then save those to the DB and would love a way to use this package.
