### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by godlikeAlex** [cheesegrits/filament-google-maps#22]
Hello, how can I choose the input language? I enter the language in .env file but it doesn't apply. (Geocomplete)

FILAMENT_GOOGLE_MAPS_LANGUAGE_CODE=en

imagine we have people working in different countries, and the whole system is in English, and for maps the language will be determined automatically? I think this is very strange

**Comment by cheesegrits** [comment]
Google recommends not setting a language on the API, rather allowing the browser settings to be used, so that's the direction I took, and only using a language setting on server side calls where there are no browser settings  But I can see that this would be something that some folk might want to override.

I'll add another setting to control the API language.

**Comment by cheesegrits** [comment]
@godlikeAlex 

OK, I released version 1.0.17 with this commit ...

https://github.com/cheesegrits/filament-google-maps/commit/1969fd9e107aa53dc5eb33f0c087bb4abe957927

... which adds a FILAMENT_GOOGLE_MAPS_API_LANGUAGE_CODE env variable you can set that controls all language usage (server side and front end API).

Lmk if this works, and I'll close this issue.

**Comment by godlikeAlex** [comment]
@cheesegrits I can't install this version, after composer require cheesegrits/filament-google-maps "v1.0.17"  

I see this result: 

composer require cheesegrits/filament-google-maps "v1.0.17"                                                                                        ─╯
./composer.json has been updated
Running composer update cheesegrits/filament-google-maps
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires cheesegrits/filament-google-maps v1.0.17 -> satisfiable by cheesegrits/filament-google-maps[v1.0.17].
    - Conclusion: don't install laravel/framework v8.41.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.42.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.42.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.43.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.44.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.45.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.45.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.46.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.47.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.48.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.48.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.48.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.49.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.49.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.49.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.50.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.51.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.52.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.53.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.53.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.54.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.55.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.56.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.57.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.58.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.59.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.60.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.61.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.62.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.63.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.64.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.65.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.66.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.67.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.68.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.68.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.69.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.70.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.70.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.70.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.71.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.72.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.73.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.73.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.73.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.74.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.75.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.76.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.76.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.76.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.77.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.77.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.78.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.78.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.79.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.80.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.81.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.82.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.6 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.7 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.8 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.9 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.10 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.11 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.12 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.13 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.14 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.15 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.16 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.17 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.18 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.19 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.20 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.21 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.22 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.23 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.24 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.25 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.26 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.83.27 (conflict analysis result)
    - cheesegrits/filament-google-maps v1.0.17 requires ryangjchandler/blade-capture-directive ^0.3 -> satisfiable by ryangjchandler/blade-capture-directive[v0.3.0].
    - Conclusion: don't install laravel/framework v8.40.0 (conflict analysis result)
    - ryangjchandler/blade-capture-directive v0.3.0 requires illuminate/contracts ^9.0|^10.0 -> satisfiable by illuminate/contracts[v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev].
    - Only one of these can be installed: illuminate/contracts[dev-master, v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev], laravel/framework[v8.40.0, ..., 8.x-dev]. laravel/framework replaces illuminate/contracts and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^8.40 -> satisfiable by laravel/framework[v8.40.0, ..., 8.x-dev].

**Comment by cheesegrits** [comment]
Hmm, no idea.  I just ran an upgrade on the local test site I use for this package, and it upgraded fine.

```
➜  fgm git:(local) ✗ composer update
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 0 installs, 26 updates, 0 removals
  - Upgrading cheesegrits/filament-google-maps (v1.0.11 => v1.0.17)
  - Upgrading filament/filament (v2.17.16 => v2.17.21)
  - Upgrading filament/forms (v2.17.16 => v2.17.21)
  - Upgrading filament/notifications (v2.17.16 => v2.17.21)
  - Upgrading filament/support (v2.17.16 => v2.17.21)
  - Upgrading filament/tables (v2.17.16 => v2.17.21)
  - Upgrading jaybizzle/crawler-detect (v1.2.113 => v1.2.114)
  - Upgrading laravel/framework (v10.3.3 => v10.5.1)
  - Upgrading laravel/pint (v1.6.0 => v1.7.0)
  - Upgrading laravel/sail (v1.21.2 => v1.21.3)
  - Upgrading league/commonmark (2.3.9 => 2.4.0)
  - Upgrading php-http/discovery (1.15.2 => 1.15.3)
  - Upgrading phpunit/phpunit (9.6.5 => 9.6.6)
  - Upgrading psy/psysh (v0.11.12 => v0.11.14)
  - Upgrading ramsey/uuid (4.x-dev bf2bee2 => 4.x-dev 8e95530)
  - Upgrading spatie/laravel-ray (1.32.3 => 1.32.4)
  - Upgrading symfony/console (v6.2.7 => v6.2.8)
  - Upgrading symfony/event-dispatcher (v6.2.7 => v6.2.8)
  - Upgrading symfony/http-foundation (v6.2.7 => v6.2.8)
  - Upgrading symfony/http-kernel (v6.2.7 => v6.2.8)
  - Upgrading symfony/mailer (v6.2.7 => v6.2.8)
  - Upgrading symfony/process (v6.2.7 => v6.2.8)
  - Upgrading symfony/routing (v6.2.7 => v6.2.8)
  - Upgrading symfony/string (v6.2.7 => v6.2.8)
  - Upgrading symfony/translation (v6.2.7 => v6.2.8)
  - Upgrading symfony/var-dumper (v6.2.7 => v6.2.8)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 31 updates, 0 removals
  - Downloading cheesegrits/filament-google-maps (v1.0.17)
  - Downloading filament/support (v2.17.21)
  - Downloading filament/notifications (v2.17.21)
  - Downloading filament/forms (v2.17.21)
  - Downloading filament/tables (v2.17.21)
  - Downloading filament/filament (v2.17.21)
  - Upgrading php-http/discovery (1.15.2 => 1.15.3): Extracting archive
  - Upgrading symfony/string (v6.2.7 => v6.2.8): Extracting archive
  - Upgrading symfony/console (v6.2.7 => v6.2.8): Extracting archive
  - Upgrading symfony/var-dumper (v6.2.7 => v6.2.8): Extracting archive
  - Upgrading symfony/routing (v6.2.7 => v6.2.8): Extracting archive
  - Upgrading symfony/process (v6.2.7 => v6.2.8): Extracting archive
  - Upgrading symfony/event-dispatcher (v6.2.7 => v6.2.8): Extracting archive
  - Upgrading symfony/mailer (v6.2.7 => v6.2.8): Extracting archive
  - Upgrading symfony/http-foundation (v6.2.7 => v6.2.8): Extracting archive
  - Upgrading symfony/http-kernel (v6.2.7 => v6.2.8): Extracting archive
  - Upgrading ramsey/uuid (4.x-dev bf2bee2 => 4.x-dev 8e95530): Extracting archive
  - Upgrading symfony/translation (v6.2.7 => v6.2.8): Extracting archive
  - Upgrading league/commonmark (2.3.9 => 2.4.0): Extracting archive
  - Upgrading laravel/framework (v10.3.0 => v10.5.1): Extracting archive
  - Upgrading spatie/laravel-package-tools (1.14.1 => 1.14.2): Extracting archive
  - Upgrading guzzlehttp/psr7 (2.4.3 => 2.4.4): Extracting archive
  - Removing cheesegrits/filament-google-maps (dev-main)
  - Installing cheesegrits/filament-google-maps (v1.0.17): Extracting archive
  - Upgrading filament/support (v2.17.14 => v2.17.21): Extracting archive
  - Upgrading filament/notifications (v2.17.14 => v2.17.21): Extracting archive
  - Upgrading filament/forms (v2.17.14 => v2.17.21): Extracting archive
  - Upgrading akaunting/laravel-money (4.0.0 => 4.0.1): Extracting archive
  - Upgrading filament/tables (v2.17.14 => v2.17.21): Extracting archive
  - Upgrading danharrin/livewire-rate-limiting (v1.0.1 => v1.1.0): Extracting archive
  - Upgrading filament/filament (v2.17.14 => v2.17.21): Extracting archive
  - Upgrading jaybizzle/crawler-detect (v1.2.113 => v1.2.114): Extracting archive
  - Upgrading laravel/pint (v1.6.0 => v1.7.0): Extracting archive
  - Upgrading laravel/sail (v1.21.1 => v1.21.3): Extracting archive
  - Upgrading psy/psysh (v0.11.12 => v0.11.14): Extracting archive
  - Upgrading myclabs/deep-copy (1.11.0 => 1.11.1): Extracting archive
  - Upgrading phpunit/phpunit (9.6.4 => 9.6.6): Extracting archive
  - Upgrading spatie/laravel-ray (1.32.3 => 1.32.4): Extracting archive

```

**Comment by cheesegrits** [comment]
Just FYI, the test site I use for it is in GitHub ...

https://github.com/cheesegrits/fgm
