### ISSUE TITLE
Location search field reverting to what I input after successful geocoding

### ISSUE THREAD

**Issue by pekka** [cheesegrits/filament-google-maps#23]
First off, thank you for this fantastic package! It is saving me so much time.

I have a Map field with fairly straightforward settings:

```
              ->mapControls(["searchBoxControl" => true])
             ->defaultLocation(config("station.default_geo_position"))
             ->clickable(false) 
             ->autocomplete('location_address')
             ->autocompleteReverse(false)

```

And it works fine: when I start typing an address, I get the autocomplete lookup as expected:

![image](https://user-images.githubusercontent.com/262464/230346081-219e9991-d8a8-4b68-8973-4efa0eedf0d7.jpeg)

However, when I click on one of the suggestions, the correct address as autocompleted by Google will show up in my search field for a fraction of a second:

![image](https://user-images.githubusercontent.com/262464/230352548-39c8b2ad-12d1-4651-a428-fa2579427d98.jpeg)

only to then revert to the stub I typed in!

![image](https://user-images.githubusercontent.com/262464/230352286-f6b5e2a8-6594-455e-9067-ed41e78cb124.png)

What am I doing wrong?
There's nothing in the error console.

**Comment by stanwarri** [comment]
I'm currently experiencing something similar. Where you able to fix this @pekka?

**Comment by pekka** [comment]
@stanwarri no, unfortunately!

**Comment by cheesegrits** [comment]
This was fixed a while ago.  Sorry about the late response.

**Comment by pekka** [comment]
Great news, thank you!
