### ISSUE TITLE
How to dynamically set countries?

### ISSUE THREAD

**Issue by elfeffe** [cheesegrits/filament-google-maps#27]
I have a select, where the user chooses the actual country (of an order).
And I need the Geocomplete to restart with the desired country.
Is that possible?

**Comment by cheesegrits** [comment]
Apologies for the slow response, I'm bad at checking github issues, I do most of my support in the Filament Discord channel.

Yes, this should be possible.  Make your country select reactive(), then on the Geocode field do something like ...

```php
Geocomplete('location')
   ->countries(fn (callable $get) => [$get->('country')]),
```

This assumes your Select returns a single two letter country code.  If not, you'll need to modify the callable response such that it returns an array of two letter country codes.

**Comment by andyov17** [comment]
Unfortunately that doesn't work, it just continues using whatever the value is when it first resolves
