### ISSUE TITLE
How to get place_id , place_name and formatted_address 

### ISSUE THREAD

**Issue by muath-ye** [cheesegrits/filament-google-maps#29]
I only got `lat` and `lng` from `Map` component , how to get other fields as json for example the following fields I can't get them
```json
{
"formatted_address":"9625+PQ6, Sana'a, Yemen",
"place_id":"ChIJL_8fsKzbAxYRQVJJJHQW21Y",
"lat":15.3522,
"lng":44.2095
}
```

**Comment by francoism90** [comment]
I have the same question, how do you get the street, city, etc.?
I know you can use `formatted_address`, however I would like to get more fields, besides `lat` and `lng`.

**Comment by cheesegrits** [comment]
You can use the reverseGeocodeUsing() callback closure, which receives the entire result from Google.  You can then do whatever you need with the formatted_address or place_id, like using $set to store it on the form (if necessary in a hidden field).

https://github.com/cheesegrits/filament-google-maps/tree/v3#reverse-geocode--place-changed-callbacks
