### ISSUE TITLE
Column not found: 1054 Unknown column 'location' in 'field list' update

### ISSUE THREAD

**Issue by EmilioBravo** [cheesegrits/filament-google-maps#3]
I added all the snippets generated by the `php artisan filament-google-maps:model-code` command. The field shows ok but when trying to save the record I get the following error `Column not found: 1054 Unknown column 'location' in 'field list' update`

**Comment by cheesegrits** [comment]
Apologies for the delay responding.  If this is still an issue, can you paste the content of your model?
