### ISSUE TITLE
Code breaks when $mapId contains hyphen

### ISSUE THREAD

**Issue by pablo-ivars-jaywing** [cheesegrits/filament-google-maps#31]
Hey, just noticed that the code breaks when the $mapId in MapTableWidget contains a hyphen, during rendering:

`if (!window.fgmjobs-map) { ...`

Just thought I'd let you know for docs purposes.

Thanks for the plugin!

**Comment by cheesegrits** [comment]
Ah, yeah, hadn't thought about that.

Should be fixed in v3.
