### ISSUE TITLE
TypeError in Actions\RadiusAction

### ISSUE THREAD

**Issue by leek** [cheesegrits/filament-google-maps#33]
When using the `Radius` action, I am getting a type error:

> Cheesegrits\FilamentGoogleMaps\Helpers\Geocoder::reverseQuery(): Return value must be of type Illuminate\Support\Collection, null returned

![CleanShot 2023-07-21 at 11 57 19](https://github.com/cheesegrits/filament-google-maps/assets/60204/b2ee2794-3984-45d5-a4d7-92d088bb9494)

**Comment by cheesegrits** [comment]
This is fixed in v3 (the Filament v3 release).  I may or may not backport the fix to v1 (the Filament v2 compatible release).
