### ISSUE TITLE
Force https request to maps API

### ISSUE THREAD

**Issue by Murkrow02** [cheesegrits/filament-google-maps#34]
Hi, thank you for the awesome plugin!

I had a problem in release with the google maps API endpoint, since the app is in a docker container behind a reverse proxy in NGINX, the following line:
`$gmaps = (Request::getScheme() ?? 'https').'://maps.googleapis.com/maps/api/js'` 
used http as default scheme even if the deployed website is using https. Consequently the request failed due to mixed content error. 

Is there any reason at all to keep the option of http to request the maps api? I had to manually patch the file to keep the app working.

**Comment by cheesegrits** [comment]
I committed a fix in v3, adding FILAMENT_GOOGLE_MAPS_FORCE_HTTPS.
