### ISSUE TITLE
Issue on Filament V3

### ISSUE THREAD

**Issue by kennyhorna** [cheesegrits/filament-google-maps#35]
Hi 👋🏼 

I tried to install the package but I get the following:
```bash

In FilamentGoogleMapsServiceProvider.php line 10:

  Class "Filament\PluginServiceProvider" not found
```

**Details**
Filament v3.0.7
filament-google-maps v1.0.25
Livewire v3.0.0-beta.6

**Comment by iAmKevinMcKee** [comment]
You can try ` "cheesegrits/filament-google-maps": "v2.0.0-alpha13",`

But right now it only works on Filament 3.0.8 or lower. It breaks at 3.0.9 and up due to a class that was removed from Filament.

**Comment by cheesegrits** [comment]
This should all be resolved.
