### ISSUE TITLE
->mapControls(['zoomControl'=>false]) not working 

### ISSUE THREAD

**Issue by dev3k** [cheesegrits/filament-google-maps#37]
I have identified the problem, which can be traced back to the line below:

https://github.com/cheesegrits/filament-google-maps/blob/a306caf81287606f22ad9fe30192a681c2d29c4c/src/Fields/Map.php#L621

The issue comes from the default behavior of performing a json_encode on the controls array.

 in the filament-google-maps.blade.php file

https://github.com/cheesegrits/filament-google-maps/blob/a306caf81287606f22ad9fe30192a681c2d29c4c/resources/views/fields/filament-google-maps.blade.php#L36

@js expects array not json encoded string

**Comment by dev3k** [comment]
and maybe this will fix  https://github.com/cheesegrits/filament-google-maps/issues/7  , but not sure as that issues is quite old for V3

**Comment by cheesegrits** [comment]
Committed a fix, will tag a release soon
