### ISSUE TITLE
Trait "Filament\Actions\Concerns\InteractsWithActions" not found

### ISSUE THREAD

**Issue by sayasuhendra** [cheesegrits/filament-google-maps#40]
I think InteractsWithActions Trait only available for filament v3.

<img width="1427" alt="image" src="https://github.com/cheesegrits/filament-google-maps/assets/4870292/a6b10c2b-7897-41c4-a6b3-6f28d68028f2">

**Comment by cheesegrits** [comment]
You must be trying to use the v3 branch on Filament v2?
