### ISSUE TITLE
Deprecated service provider causes composer error (Filament v3)

### ISSUE THREAD

**Issue by nsrosenqvist** [cheesegrits/filament-google-maps#43]
When using the package with Filament v3, you get the following error:

![Skärmbild 2023-08-21 220657](https://github.com/cheesegrits/filament-google-maps/assets/1303475/a49e3f13-5a67-41cb-ac23-b92dcea03d2e)

According to the [upgrade guide](https://filamentphp.com/docs/3.x/support/plugins/getting-started#upgrading-existing-plugins), this class should be replace with ` Spatie\LaravelPackageTools\PackageServiceProvider`.

**Comment by nsrosenqvist** [comment]
It appears that the plugin also doesn't take into account the upgrades in Livewire 3. Is there a ticket tracking Filament v3 support?

**Comment by middaparka** [comment]
@nsrosenqvist Are you using the v3 branch?

i.e.: https://github.com/cheesegrits/filament-google-maps/tree/v3

**Comment by nsrosenqvist** [comment]
@middaparka my bad, I didn't see that there was a branch for v3. I'll try it out!
