### ISSUE TITLE
Commands: Models not found if name matches facade

### ISSUE THREAD

**Issue by josefbehr** [cheesegrits/filament-google-maps#9]
If one tries to run the commands (e.g. model-code) for a model whose name matches an existing Facade (e.g. Event), the command tries to use the Facade instead of the model due to this code

```
		try
		{
			$model = new $modelName();
		}
		catch (\Throwable $e)
		{
			try
			{
				$model = new ('\\App\\Models\\' . $modelName)();
			}
			catch (\Throwable $e)
			{
				echo "Can't find class {$modelName} or \\App\\Models\\{$modelName}\n";

				return static::INVALID;
			}
		}
```

I think the first try should be removed completely, as I see no reason to try and get an instance of a model on global namespace. This will lead to problems for any model that shares a name with a facade, and commands then can't be run for those models. Instead, the command should always use the App\\Models namespace (or support an option for differing namespaces).

**Comment by cheesegrits** [comment]
Fixed in #11
